### ISSUE TITLE
Add support for read only cache

### ISSUE THREAD

**Issue by juddgaddie** [robinpellegrims/pellegrims#170]
CI writes to cache and users read from it.
```
    const ENV_READ_ONLY = 'NX_CACHE_S3_READONLY';
    const readonlyCache = getEnv(ENV_READ_ONLY) ?? false;
   const putObject = async (filename, buffer) => {....}
    ...
    storeFile: readOnlyCache ? putObject : (filename, buffer) => {},
```

**Additional context**
Some users have very limited upload speeds on their home internet connections.
We don't want the security risk of users being able to polute/poisoin the cache but benefit from cached files.

**Comment by robinpellegrims** [comment]
Sounds like something we can easily add. do you want to provide a PR?

**Comment by rathpc** [comment]
@robinpellegrims I created a PR to address this https://github.com/robinpellegrims/pellegrims/pull/173

Please let me know if there is anything missing there to get it merged. Thanks!
