### ISSUE TITLE
Allow parsing of env variables from top-level env-like files

### ISSUE THREAD

**Issue by terrymun** [robinpellegrims/pellegrims#223]
**Is your feature request related to a problem? Please describe.**
I noticed that the plugin only reads the variables defined in `.env` file. However, sometimes we might need to use a different S3 bucket or region for a different environment (with variables stored in `.env.local`, for example), and it is not possible to make this switch.

In [Nx's article on how it reads in environment variables](https://nx.dev/recipes/environment-variables/define-environment-variables), it follows the list when reading them from top-level (i.e. at the monorepo root) env-related files:

- `.env.[target-name].[configuration-name]`
- `.[target-name].[configuration-name].env`
- `.env.[configuration-name]`
- `.[configuration-name].env`
- `.env.[target-name]`
- `.[target-name].env`
- `.local.env`
- `.env.local`
- `.env`

**Describe the solution you'd like**
It would be nice if the plugin can read/merge env variables from different env files the same way as Nx does, instead of simply reading from `process.env` directly, which only loads the variables defined in `.env`

**Describe alternatives you've considered**
There is really no other way to load env variables in, so right now we are forced to maintain a root `.env` file even though we typically have variables defined in `.env.local`

**Additional context**
n.a.

**Comment by robinpellegrims** [comment]
Sure, we could implement something like nx does here: https://github.com/nrwl/nx/blob/fa513731d4e6a960f112a5af6b0d725b2e624b36/packages/nx/src/tasks-runner/forked-process-task-runner.ts#L402

Would you like to provide a PR?

**Comment by robinpellegrims** [comment]
`dotenvPath` option is now supported by the base `nx-remotecache-custom` configuration. See https://github.com/NiklasPor/nx-remotecache-custom#advanced-configuration.

Feel free to reopen if this doesn't solve your issue.
