### ISSUE TITLE
Update nx-remotecache-custom to v5

### ISSUE THREAD

**Issue by EvgeniyKumachev** [robinpellegrims/pellegrims#237]
**Is your feature request related to a problem? Please describe.**
Hi, i've encountered a bug described [here](https://github.com/NiklasPor/nx-remotecache-custom/issues/23), submitted pr and is was merged but released with new major version so bumping version in `@pellegrims/nx-remotecache-s3` is also required. I can make a pr here but seeing as this is something like a personal monorepo i'd rather create issue first

**Describe the solution you'd like**
Upgrade `nx-remotecache-custom` to `5.0.0` in `@pellegrims/nx-remotecache-s3` or add it to peer deps

**Comment by robinpellegrims** [comment]
sure, feel free to create a PR
