### ISSUE TITLE
nx-remotecache-custom dependency version is declared as ^17.0.0, should be ^5.0.0

### ISSUE THREAD

**Issue by cuddlecake** [robinpellegrims/pellegrims#263]
Hi, as in the title, the dependency to nx-remotecache-custom is currently wrong

Change got introduced here, probably because of automatic migration:
https://github.com/robinpellegrims/pellegrims/pull/249/files

**Comment by robinpellegrims** [comment]
Actually, nx-remotecache-custom switched to mirroring the version of nx, so they went from v5 to v17 when upgrading to nx v17.

See their changelog on  https://github.com/NiklasPor/nx-remotecache-custom/blob/main/CHANGELOG.md
