### ISSUE TITLE
[Question] Should the Remote Cache be Sharing?

### ISSUE THREAD

**Issue by tylerkilburn** [robinpellegrims/pellegrims#265]
Does nx-remotecache-s3 have the ability to share cached values between local machines and a CI server.  I am observing that the hash values seem to be unique for the machine running it and don't seem like they are sharing.

eg, I build on my local, it caches to s3.  I push up.  CI worker does not recognize as a cached value and builds and caches its own.

Is this expected?  Is there a way to configure this so the cache is shared?

Thanks a bunch!

**Comment by tylerkilburn** [comment]
Disregard, I am a dummy.  Traced through the code of @pellegrims/nx-remotecache-s3 and nx-remotecache-custom after additional troubleshooting found my issue to be a .nxignore and nx.json misconfig.  Thank you for the awesome library! 🙏

**Comment by robinpellegrims** [comment]
No problem, this might help other people in the future, Glad you found the issue!
