### ISSUE TITLE
Support NX version 20

### ISSUE THREAD

**Issue by el-davo** [robinpellegrims/pellegrims#282]
**Is your feature request related to a problem? Please describe.**
After upgrading to version 20 we noticed that @pellegrims/nx-remotecache-s3 package no longer reads remote cache

**Describe the solution you'd like**
Support NX version 20

**Comment by privatenumber** [comment]
Looks like it was released later that day:
https://github.com/NiklasPor/nx-remotecache-custom/releases/tag/v20.0.0

**Comment by robinpellegrims** [comment]
This was released in [8.1.0.](https://github.com/robinpellegrims/pellegrims/releases/tag/nx-remotecache-s3-8.1.0)
