### ISSUE TITLE
question(nx-remotecache-s3): aws credentials

### ISSUE THREAD

**Issue by hoonoh** [robinpellegrims/pellegrims#62]
Hello,

Is there a specific reason behind why access key id & secret access key needs to be defined via either options or environment variable? 
https://github.com/robinpellegrims/pellegrims/blob/7a6fd7c4035b16a81a9be0126cec29c1f45c6ec1/libs/nx-remotecache-s3/src/lib/nx-remotecache-s3.ts#L25-L33
I was thinking of using this plugin on EC2 with IAM role (AWS CodeBuild) and noticed currently the above lines were blocking this type of usage. 
I think it might be better to remove the checks and let it fallback to aws-sdk-v3 credential provider if user defined AWS credentials are unavailable. I made an example patch [here](https://github.com/hoonoh/pellegrims/commit/34f739fdb9c9f204a939313533d51910576c65a6)

**Comment by robinpellegrims** [comment]
I'm personally using it with Backblaze B2 so there both parameters are mandatory but I'm sure there will be an error from the B2 backend anyway if they are not set. So feel free to open a PR to make it compatible with your use case.

**Comment by hoonoh** [comment]
> I'm personally using it with Backblaze B2 so there both parameters are mandatory but I'm sure there will be an error from the B2 backend anyway if they are not set. So feel free to open a PR to make it compatible with your use case.

Ah I see. I will open a PR with the changes :smile:
